{% set name = "perl-encode" %}
{% set version = "3.21" %}
{% set sha256 = "eacf71c5eb49e0e590de797f1982d7fb95d8481e4d13c3ce79eb32ef9373b3db" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DA/DANKOGAI/Encode-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("perl-encode", max_pin="x") }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make

  host:
    - perl
    - perl-storable
    - perl-extutils-makemaker
    - perl-exporter
    - perl-parent
    #- perl-test-more

  run:
    - perl
    - perl-storable
    - perl-exporter
    - perl-parent

test:
  imports:
    - Encode
  commands:
    - perl -we 'use Encode::Alias'  # version does not match that of Encode

about:
  home: http://metacpan.org/pod/Encode
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: 'character encodings in Perl'

extra:
  recipe-maintainers:
    - xileF1337
    - cbrueffer
